// <auto-generated by="the Blazor I18n Text compiler" />
namespace ChineseDictionary.I18nText
{
    public partial class Strings : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "ru";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Канвас"</summary>
        public string Canvas;

        /// <summary>"Карточки"</summary>
        public string Flashcards;

        /// <summary>"Старт"</summary>
        public string Home;

        /// <summary>"Поиск"</summary>
        public string Search;
    }
}
