// <auto-generated by="the Blazor I18n Text compiler" />
namespace ChineseDictionary.I18nText
{
    public partial class Strings : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "ru";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"О blazor"</summary>
        public string About;

        /// <summary>"Рукописный ввод"</summary>
        public string Canvas;

        /// <summary>"Очистить"</summary>
        public string Clear;

        /// <summary>"Не помню"</summary>
        public string DontRremember;

        /// <summary>"Примеры:"</summary>
        public string Examples;

        /// <summary>"Карточки"</summary>
        public string Flashcards;

        /// <summary>"4 варианта"</summary>
        public string FourOptions;

        /// <summary>"Группа карточек:"</summary>
        public string GroupOfFlashcards;

        /// <summary>"Привет! :) "</summary>
        public string HelloWorld;

        /// <summary>"Старт"</summary>
        public string Home;

        /// <summary>"Загрузка..."</summary>
        public string Loading;

        /// <summary>"Больше"</summary>
        public string More;

        /// <summary>"Далее"</summary>
        public string Next;

        /// <summary>"Номер слова:"</summary>
        public string NumberOfWords;

        /// <summary>"Синонимы:"</summary>
        public string RelativeWords;

        /// <summary>"Восстановить"</summary>
        public string Restore;

        /// <summary>"Обзор"</summary>
        public string Review;

        /// <summary>"Помню"</summary>
        public string Rremember;

        /// <summary>"Поиск"</summary>
        public string Search;

        /// <summary>"Выберите тип тренировки..."</summary>
        public string SelectTypeOfTrain;

        /// <summary>"Извините, по этому адресу ничего нет."</summary>
        public string Sorry;

        /// <summary>"Закончить тренировку"</summary>
        public string StopTrain;

        /// <summary>"Пожалуйста, пройдите [опрос]({0}) и поделитесь с нами своим мнением."</summary>
        public string SurveyPrompt;

        /// <summary>"Как Blazor работает?"</summary>
        public string SurveyTitle;

        /// <summary>"Тренироваться!"</summary>
        public string Train;

        /// <summary>"Перевод:"</summary>
        public string Translation;

        /// <summary>"Добро пожаловать в ChineseDictionary! Мы являемся лучшим словарем по мнению Билла Гейтса."</summary>
        public string WelcomeToYourNewApp;
    }
}
